//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amandman
    {
        public Amandman()
        {
            this.ZakljucakAmandmen = new HashSet<ZakljucakAmandman>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Postavio { get; set; }
        public string Tekst { get; set; }
        public string Odnosi_se { get; set; }
        public string Obrazlozenje { get; set; }
        public Nullable<int> Dokument { get; set; }
        public Nullable<bool> Blagovremen { get; set; }
        public Nullable<bool> odustao { get; set; }
        public Nullable<System.DateTime> vreme_odustao { get; set; }
    
        public virtual DOKUMENTA DOKUMENTA { get; set; }
        public virtual KORISNIK KORISNIK { get; set; }
        public virtual ICollection<ZakljucakAmandman> ZakljucakAmandmen { get; set; }
    }
}
