//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumenta_Subjekat
    {
        public int ID { get; set; }
        public Nullable<int> ID_DOKUMENTA { get; set; }
        public Nullable<int> ID_SUBJEKAT { get; set; }
        public Nullable<bool> KORAK_ZAVRSEN { get; set; }
        public Nullable<int> REDNI_BROJ { get; set; }
        public string Postavio_korisnik { get; set; }
        public Nullable<System.DateTime> Vreme { get; set; }
        public Nullable<int> Brojac { get; set; }
        public Nullable<int> ID_Verzija_Dokumenta { get; set; }
    
        public virtual DOKUMENTA DOKUMENTA { get; set; }
        public virtual DOKUMENTA DOKUMENTA1 { get; set; }
        public virtual SUBJEKAT SUBJEKAT { get; set; }
    }
}
