//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentar_Tacka
    {
        public int ID { get; set; }
        public string Komentar { get; set; }
        public string Postavio { get; set; }
        public Nullable<System.DateTime> Vreme { get; set; }
        public Nullable<int> Tacka { get; set; }
    
        public virtual Tacke_Dnevnog_Reda Tacke_Dnevnog_Reda { get; set; }
    }
}
