//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;

    public partial class KORISNIK
    {
        public KORISNIK()
        {
            this.Amandmen = new HashSet<Amandman>();
            this.Amandmani_pomocna = new HashSet<Amandmani_pomocna>();
            this.Hitan_Postupak = new HashSet<Hitan_Postupak>();
            this.Izmene_DnReda = new HashSet<Izmene_DnReda>();
            this.KORISNIK_SUBJEKAT = new HashSet<KORISNIK_SUBJEKAT>();
            this.Logovis = new HashSet<Logovi>();
            this.Masovnas = new HashSet<Masovna>();
            this.MasovniMails = new HashSet<MasovniMail>();
            this.Porukes = new HashSet<Poruke>();
            this.Pozvani_Korisnici = new HashSet<Pozvani_Korisnici>();
            this.Pristup_Korisnik = new HashSet<Pristup_Korisnik>();
            this.SEDNICEs = new HashSet<SEDNICE>();
        }

        public int ID { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string JMBG { get; set; }
        public string FUNKCIJA { get; set; }
        public string USERNAME { get; set; }
        public string LOZINKA { get; set; }
        public string MAIL { get; set; }
        public string MOBILNI { get; set; }
        public Nullable<bool> Aktivan { get; set; }
        public Nullable<int> Potrebna_potvrda { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> sluzbeno { get; set; }
        public string Naziv
        {
            get { return PREZIME + ' ' + IME ; }
        }

        public virtual ICollection<Amandman> Amandmen { get; set; }
        public virtual ICollection<Amandmani_pomocna> Amandmani_pomocna { get; set; }
        public virtual ICollection<Hitan_Postupak> Hitan_Postupak { get; set; }
        public virtual ICollection<Izmene_DnReda> Izmene_DnReda { get; set; }
        public virtual ICollection<KORISNIK_SUBJEKAT> KORISNIK_SUBJEKAT { get; set; }
        public virtual ICollection<Logovi> Logovis { get; set; }
        public virtual ICollection<Masovna> Masovnas { get; set; }
        public virtual ICollection<MasovniMail> MasovniMails { get; set; }
        public virtual ICollection<Poruke> Porukes { get; set; }
        public virtual ICollection<Pozvani_Korisnici> Pozvani_Korisnici { get; set; }
        public virtual ICollection<Pristup_Korisnik> Pristup_Korisnik { get; set; }
        public virtual ICollection<SEDNICE> SEDNICEs { get; set; }
    }
}
