//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logovi
    {
        public int ID { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> vreme { get; set; }
        public Nullable<int> korisnikID { get; set; }
    
        public virtual KORISNIK KORISNIK { get; set; }
    }
}
