//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int ID { get; set; }
        public Nullable<int> Sednica_ID { get; set; }
        public string Mailovi { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual SEDNICE SEDNICE { get; set; }
    }
}
