//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozvani_Korisnici
    {
        public int id { get; set; }
        public Nullable<int> Korisnik_ID { get; set; }
        public Nullable<int> Sednica_ID { get; set; }
        public Nullable<bool> Potvrdio { get; set; }
        public Nullable<System.DateTime> Vreme_potvrde { get; set; }
        public Nullable<bool> Mail { get; set; }
        public Nullable<bool> SMS { get; set; }
        public string Komentar { get; set; }
        public Nullable<bool> Prisustvuje { get; set; }
        public Nullable<bool> Prikaz { get; set; }
        public Nullable<System.DateTime> Datum_SMS { get; set; }
        public Nullable<System.DateTime> Datum_Mail { get; set; }
        public Nullable<System.DateTime> Vreme_Pozvan { get; set; }
        public Nullable<bool> Sistem { get; set; }
    
        public virtual KORISNIK KORISNIK { get; set; }
        public virtual SEDNICE SEDNICE { get; set; }
    }
}
