//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pristup_Korisnik
    {
        public int Id { get; set; }
        public Nullable<int> Id_Korisnik { get; set; }
        public Nullable<int> Sednice { get; set; }
        public Nullable<int> Zapisnik { get; set; }
        public Nullable<int> Dokumenta { get; set; }
        public Nullable<int> Clanovi { get; set; }
        public Nullable<int> Lozinka { get; set; }
        public Nullable<int> Organ { get; set; }
        public Nullable<int> Statusi { get; set; }
        public Nullable<int> Pozivanje { get; set; }
        public Nullable<int> Amandmani { get; set; }
        public Nullable<int> Dnevni_red { get; set; }
        public Nullable<bool> IzmenaDnRedaPosle24Sata { get; set; }
        public Nullable<bool> Komentari { get; set; }
    
        public virtual KORISNIK KORISNIK { get; set; }
    }
}
