//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronskeSednice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisnik
    {
        public int Id { get; set; }
        public string Zapisnik1 { get; set; }
        public string Audio_zapis { get; set; }
        public Nullable<int> Broj_sednice { get; set; }
    
        public virtual SEDNICE SEDNICE { get; set; }
    }
}
