//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElektronskeSednice.Resources.View.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracija.
        /// </summary>
        public static string Administracija {
            get {
                return ResourceManager.GetString("Administracija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronske sednice opštine Inđija.
        /// </summary>
        public static string AplicationName {
            get {
                return ResourceManager.GetString("AplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ćir.
        /// </summary>
        public static string Cyr {
            get {
                return ResourceManager.GetString("Cyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ćirilica.
        /// </summary>
        public static string Cyrillic {
            get {
                return ResourceManager.GetString("Cyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenta.
        /// </summary>
        public static string Dokumenta {
            get {
                return ResourceManager.GetString("Dokumenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string Izmeni {
            get {
                return ResourceManager.GetString("Izmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latinica.
        /// </summary>
        public static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latinica.
        /// </summary>
        public static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavite se.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string Nazad {
            get {
                return ResourceManager.GetString("Nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        public static string Pocetna {
            get {
                return ResourceManager.GetString("Pocetna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrujte se.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Sacuvaj {
            get {
                return ResourceManager.GetString("Sacuvaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sednice.
        /// </summary>
        public static string Sednice {
            get {
                return ResourceManager.GetString("Sednice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronske sednice opštine Inđija.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
